// Curated, dependency-free emoji set for the chat picker. Grouped by category with
// search keywords. Not exhaustive (that's what a library is for) — a useful common set.
export interface EmojiEntry {
  char: string
  keywords: string
}

export interface EmojiCategory {
  id: string
  label: string
  icon: string
  emojis: EmojiEntry[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys',
    icon: '😀',
    emojis: [
      { char: '😀', keywords: 'grin happy smile' },
      { char: '😃', keywords: 'happy smile joy' },
      { char: '😄', keywords: 'happy laugh' },
      { char: '😁', keywords: 'grin beam' },
      { char: '😆', keywords: 'laugh haha' },
      { char: '😅', keywords: 'sweat laugh nervous' },
      { char: '🤣', keywords: 'rofl laughing rolling' },
      { char: '😂', keywords: 'joy tears laughing' },
      { char: '🙂', keywords: 'slight smile' },
      { char: '😉', keywords: 'wink' },
      { char: '😊', keywords: 'blush smile happy' },
      { char: '😇', keywords: 'angel innocent' },
      { char: '🥰', keywords: 'love hearts adore' },
      { char: '😍', keywords: 'heart eyes love' },
      { char: '😘', keywords: 'kiss love' },
      { char: '😜', keywords: 'tongue wink silly' },
      { char: '🤪', keywords: 'zany crazy silly' },
      { char: '🤔', keywords: 'thinking hmm' },
      { char: '🤗', keywords: 'hug hugging' },
      { char: '😎', keywords: 'cool sunglasses' },
      { char: '🥳', keywords: 'party celebrate' },
      { char: '😢', keywords: 'cry sad tear' },
      { char: '😭', keywords: 'sob cry bawling' },
      { char: '😤', keywords: 'huff angry steam' },
      { char: '😡', keywords: 'angry mad rage' },
      { char: '🥺', keywords: 'pleading puppy please' },
      { char: '😴', keywords: 'sleep tired' },
      { char: '🤯', keywords: 'mind blown shocked' },
      { char: '😬', keywords: 'grimace awkward' },
      { char: '🙄', keywords: 'eye roll' },
    ],
  },
  {
    id: 'gestures',
    label: 'Gestures',
    icon: '👍',
    emojis: [
      { char: '👍', keywords: 'thumbs up like yes' },
      { char: '👎', keywords: 'thumbs down no dislike' },
      { char: '👏', keywords: 'clap applause' },
      { char: '🙌', keywords: 'raised hands praise' },
      { char: '👌', keywords: 'ok perfect' },
      { char: '🤌', keywords: 'pinched fingers' },
      { char: '✌️', keywords: 'peace victory' },
      { char: '🤞', keywords: 'fingers crossed luck' },
      { char: '🤝', keywords: 'handshake deal' },
      { char: '🙏', keywords: 'pray thanks please' },
      { char: '👋', keywords: 'wave hi bye hello' },
      { char: '🤙', keywords: 'call me shaka' },
      { char: '💪', keywords: 'muscle strong flex' },
      { char: '👊', keywords: 'fist bump punch' },
      { char: '✊', keywords: 'raised fist' },
      { char: '🫶', keywords: 'heart hands love' },
      { char: '👀', keywords: 'eyes looking' },
      { char: '🫡', keywords: 'salute respect' },
    ],
  },
  {
    id: 'hearts',
    label: 'Hearts',
    icon: '❤️',
    emojis: [
      { char: '❤️', keywords: 'red heart love' },
      { char: '🧡', keywords: 'orange heart' },
      { char: '💛', keywords: 'yellow heart' },
      { char: '💚', keywords: 'green heart' },
      { char: '💙', keywords: 'blue heart' },
      { char: '💜', keywords: 'purple heart' },
      { char: '🖤', keywords: 'black heart' },
      { char: '🤍', keywords: 'white heart' },
      { char: '💖', keywords: 'sparkling heart' },
      { char: '💗', keywords: 'growing heart' },
      { char: '💕', keywords: 'two hearts love' },
      { char: '💔', keywords: 'broken heart' },
      { char: '❣️', keywords: 'heart exclamation' },
      { char: '💯', keywords: 'hundred perfect score' },
    ],
  },
  {
    id: 'nature',
    label: 'Nature',
    icon: '🐶',
    emojis: [
      { char: '🐶', keywords: 'dog puppy' },
      { char: '🐱', keywords: 'cat kitten' },
      { char: '🦊', keywords: 'fox' },
      { char: '🐻', keywords: 'bear' },
      { char: '🐼', keywords: 'panda' },
      { char: '🐵', keywords: 'monkey' },
      { char: '🦁', keywords: 'lion' },
      { char: '🐸', keywords: 'frog' },
      { char: '🐧', keywords: 'penguin' },
      { char: '🦄', keywords: 'unicorn' },
      { char: '🌸', keywords: 'flower blossom' },
      { char: '🌹', keywords: 'rose flower' },
      { char: '🌟', keywords: 'star glowing' },
      { char: '⭐', keywords: 'star' },
      { char: '🔥', keywords: 'fire lit hot' },
      { char: '🌈', keywords: 'rainbow' },
      { char: '☀️', keywords: 'sun sunny' },
      { char: '⚡', keywords: 'lightning bolt' },
    ],
  },
  {
    id: 'food',
    label: 'Food',
    icon: '🍕',
    emojis: [
      { char: '🍕', keywords: 'pizza' },
      { char: '🍔', keywords: 'burger' },
      { char: '🍟', keywords: 'fries' },
      { char: '🌮', keywords: 'taco' },
      { char: '🍣', keywords: 'sushi' },
      { char: '🍜', keywords: 'noodles ramen' },
      { char: '🍦', keywords: 'ice cream' },
      { char: '🍩', keywords: 'donut' },
      { char: '🍪', keywords: 'cookie' },
      { char: '🎂', keywords: 'cake birthday' },
      { char: '☕', keywords: 'coffee tea' },
      { char: '🍺', keywords: 'beer drink' },
      { char: '🍷', keywords: 'wine' },
      { char: '🥂', keywords: 'cheers toast' },
      { char: '🍎', keywords: 'apple fruit' },
      { char: '🍌', keywords: 'banana fruit' },
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    icon: '🎉',
    emojis: [
      { char: '🎉', keywords: 'party tada celebrate' },
      { char: '🎊', keywords: 'confetti celebrate' },
      { char: '🎈', keywords: 'balloon' },
      { char: '🎁', keywords: 'gift present' },
      { char: '🏆', keywords: 'trophy win' },
      { char: '🥇', keywords: 'gold medal first' },
      { char: '⚽', keywords: 'soccer football' },
      { char: '🏀', keywords: 'basketball' },
      { char: '🎮', keywords: 'game controller' },
      { char: '🎵', keywords: 'music note' },
      { char: '🎸', keywords: 'guitar music' },
      { char: '✈️', keywords: 'plane travel flight' },
      { char: '🚀', keywords: 'rocket launch' },
      { char: '🏠', keywords: 'house home' },
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    icon: '💡',
    emojis: [
      { char: '💡', keywords: 'idea bulb light' },
      { char: '📱', keywords: 'phone mobile' },
      { char: '💻', keywords: 'laptop computer' },
      { char: '⌨️', keywords: 'keyboard' },
      { char: '📷', keywords: 'camera' },
      { char: '🎥', keywords: 'video camera movie' },
      { char: '🔒', keywords: 'lock secure private' },
      { char: '🔑', keywords: 'key' },
      { char: '📌', keywords: 'pin' },
      { char: '✅', keywords: 'check done yes' },
      { char: '❌', keywords: 'cross no x' },
      { char: '⏰', keywords: 'alarm clock time' },
      { char: '💰', keywords: 'money bag' },
      { char: '📎', keywords: 'paperclip attach' },
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    icon: '✨',
    emojis: [
      { char: '✨', keywords: 'sparkles shiny' },
      { char: '⭐', keywords: 'star' },
      { char: '❗', keywords: 'exclamation important' },
      { char: '❓', keywords: 'question' },
      { char: '💢', keywords: 'anger symbol' },
      { char: '💤', keywords: 'sleep zzz' },
      { char: '🔔', keywords: 'bell notification' },
      { char: '🚫', keywords: 'no banned forbidden' },
      { char: '⚠️', keywords: 'warning caution' },
      { char: '♻️', keywords: 'recycle' },
      { char: '✔️', keywords: 'check mark' },
      { char: '➕', keywords: 'plus add' },
      { char: '🔴', keywords: 'red circle' },
      { char: '🟢', keywords: 'green circle' },
    ],
  },
]

// Flat list for keyword search.
export const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis)
